services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - '8001:8001'
    command: '-jar DynamoDBLocal.jar -sharedDb'
    networks:
      - store-network

  dynamodb-init:
    image: amazon/aws-cli:latest
    container_name: dynamodb-init
    volumes:
      - ./scripts/init-dynamodb.sh:/init-dynamodb.sh
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8001
      - DYNAMODB_TABLE_NAME=${DYNAMODB_TABLE_NAME}
    entrypoint: ['/bin/sh', '/init-dynamodb.sh']
    depends_on:
      - dynamodb-local
    networks:
      - store-network

  store-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: microservice-store
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - /app/node_modules
    env_file:
      - .env
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8001
    depends_on:
      dynamodb-init:
        condition: service_completed_successfully
    networks:
      - store-network
    restart: on-failure

networks:
  store-network:
    driver: bridge
