services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    command: '-jar DynamoDBLocal.jar -sharedDb'
    networks:
      - store-network

  dynamodb-init:
    image: amazon/aws-cli:latest
    container_name: dynamodb-init
    volumes:
      - ./scripts/init-dynamodb.sh:/init-dynamodb.sh
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - DYNAMODB_TABLE_NAME=${DYNAMODB_TABLE_NAME}
    entrypoint: ['/bin/sh', '/init-dynamodb.sh']
    depends_on:
      - dynamodb-local
    networks:
      - store-network

  store-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: microservice-store
    ports:
      - '${APP_PORT:-3000}:3000'
    volumes:
      - ./src:/app/src
      - ./test:/app/test
      - /app/node_modules
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - DYNAMODB_TABLE_NAME=${DYNAMODB_TABLE_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
      - API_KEY=${API_KEY}
      - CATEGORY_PATH_PARAMETER_NAME=${CATEGORY_PATH_PARAMETER_NAME}
      - CATEGORY_API_KEY_SECRET_NAME=${CATEGORY_API_KEY_SECRET_NAME}
    depends_on:
      dynamodb-init:
        condition: service_completed_successfully
    networks:
      - store-network
    restart: on-failure

networks:
  store-network:
    driver: bridge
